language: python
python:
    - "3.3"
    - "3.4"

env:
    - DB=sqlite
    - DB=postgres

before_script:
  - psql -c 'create database inboxen;' -U postgres

install:
    - if [[ $DB == postgres ]]; then pip install -q psycopg2; fi
    - pip install -q -r requirements.txt

script: python manage.py test --settings=inboxen.tests.settings

notifications:
    irc:
        channels:
            - "ircs://irc.megworld.co.uk:9000#inboxen"
        use_notice: true
